### PR TITLE
Update to PHPUnit 10

### PR DESCRIPTION
**Pull request by Slamdunk**
Blocked by https://github.com/laminas/laminas-servicemanager/pull/183

### CODE REVIEW

**Comment by Ocramius** [comment]
Needs a small rebase, then good to go :+1:

**Comment by Slamdunk** [comment]
Done

**Review by Ocramius — APPROVED** [review]
LGTM :+1: 

Thanks @Slamdunk!

**Comment by Ocramius** [comment]
@boesing I'll hold back a release based on your feedback: you did loads of patches, and I lost the flow here :S

**Pull request merged**
