### PR TITLE
[WIP] Bump PHPUnit:^9

### PR DESCRIPTION
**Pull request by sasezaki**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

Currently, I feel needs to remove deprecations (eg.  in AbstractPluginManager) before update to PHPUnit 9.

Because, `assertAttributeSame()` is used to check raising E_USER_DEPRECATED.

Introduced BackportAssertionsTrait should be removed before merge.

### CODE REVIEW

**Comment by GeeH** [comment]
Hey @sasezaki thank you so much for the PR! I'm in the process of cleaning up and modernising this component and will be upgrading the version of PHPUnit in a PR this week -- it's on my list of things to do as part of #44. I hope you didn't spend too much time on this but hopefully as it's WIP there wasn't too much duplication of work.

**Comment by GeeH** [comment]
I changed my mind

**Comment by GeeH** [comment]
You've done amazing work here @sasezaki please let me know if you'd like to collab on this I didn't realise the context of this work!

**Comment by snapshotpl** [comment]
@sasezaki are you need help with this? Looks very promising and I need this support in #51 so I don't want to duplicate your work.

Looks like fails only on 7.3, but on develop branch we dropped support for that, so if you update branch then should be green :)

**Comment by sasezaki** [comment]
sorry to very late reply.
currently, I don't have enough time to spare.
So, I hope someone to work on this instead.

**Comment by boesing** [comment]
Closed in favor of #56

**Pull request closed without merging**
