### PR TITLE
Psalm support

### LINKED ISSUE #54: Psalm integration
### Feature Request

|    Q        |   A
|------------ | ------
| QA    | yes

#### Summary

As decided during the [Technical-Steering-Committee Meeting on August 3rd, 2020](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-static-analysis-tooling), Laminas wants to implement [vimeo/psalm](https://github.com/vimeo/psalm) in all packages.

Implementing psalm is quite easy.

#### Required
- [ ] Create a `.psalm.xml.dist` in the project root
- [ ] Copy and paste the contents from this [psalm.xml.dist](https://github.com/mezzio/repo-template/blob/6124090610ef1c6d6b0c80a063cafacc3ec68f38/psalm.xml.dist)
- [ ] Run `$ composer require vimeo/psalm`
- [ ] Run `$ vendor/bin/psalm --set-baseline=psalm-baseline.xml`
- [ ] Add a composer script `static-analysis` with the command `psalm --shepherd --stats`
- [ ] Add a new line to `script:` in `.travis.yml`: `- if [[ $TEST_COVERAGE == 'true' ]]; then composer static-analysis ; fi`
- [ ] Remove phpstan from the project (`phpstan.neon.dist`, `.travis.yml` entry, `composer.json` `require-dev` and `scripts`)

##### Optional
- [ ] Fix as many psalm errors as possible.

### PR DESCRIPTION
**Pull request by fezfez**
fix #54 

* [x]  Create a `.psalm.xml.dist` in the project root
* [x] Copy and paste the contents from this [psalm.xml.dist](https://github.com/mezzio/repo-template/blob/6124090610ef1c6d6b0c80a063cafacc3ec68f38/psalm.xml.dist)
* [x] Run `$ composer require vimeo/psalm`
* [x] Run `$ vendor/bin/psalm --set-baseline=psalm-baseline.xml`
* [x] Add a composer script `static-analysis` with the command `psalm --shepherd --stats`
* [x] Add a new line to `script:` in `.travis.yml`: `- if [[ $TEST_COVERAGE == 'true' ]]; then composer static-analysis ; fi`
* [x] Remove phpstan from the project (`phpstan.neon.dist`, `.travis.yml` entry, `composer.json` `require-dev` and `scripts`)

composer ^2.0 is now required in dev environnement

### CODE REVIEW

**Comment by fezfez** [comment]
Hello @weierophinney, can you check this ? Thanks !

**Comment by weierophinney** [comment]
@fezfez —

Please rebase your patch to add sign-off on each commit; [read how in our contributor documentation](https://github.com/laminas/.github/blob/master/CONTRIBUTING.md#adding-signoffs-after-the-fact).

**Comment by boesing** [comment]
@weierophinney we might want to have #64 first.
I still think that a new major at this point in time will require a lot of man power to prepare all components to be compatible.

seeing the activity in the last 3 months does not make me think that we should go that road for now.

**Comment by fezfez** [comment]
@boesing #64 is merged now

**Comment by fezfez** [comment]
Ping! 🙃

**Comment by boesing** [comment]
I'll merge this when we've implemented GHA for CI.
For more details, see laminas/technical-steering-committee#61

There is DCO missing, to fix that, follow the steps which are described [here](https://github.com/laminas/laminas-servicemanager/pull/65/checks?check_run_id=1556802874)

We will discuss about how we want to proceed with this project in the next TSC meeting (next monday). After this, we can decide how to proceed with this PR aswell.

I think, you should target this PR against 3.7.x for now as we might drop 4.0.x and either re-create it from 3.7.x **or** we keep 3.x until we have a proper vision for this component.

**Comment by weierophinney** [comment]
I've rebased this against current 4.0.x; however, the GHA workflow has not yet made it to the 4.0.x branch, so we need to wait a bit longer.

@fezfez We still need the sign-off in your commit, please; please see my earlier comment for how to do that.

**Comment by boesing** [comment]
Thanks, @fezfez

**Pull request merged**
