### PR TITLE
Remove check for `php:<7`, since support was dropped

### PR DESCRIPTION
**Pull request by internalsystemerror**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Since support for PHP < 7.3 was dropped in v3.6 of this library, the check for PHP < 7 can be removed.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
@internalsystemerror could you check these two CS failures, please?

```
Error: Type explode is not used in this file.
Error: Type strpos is not used in this file.
```

**Comment by internalsystemerror** [comment]
> @internalsystemerror could you check these two CS failures, please?
> 
> ```
> Error: Type explode is not used in this file.
> Error: Type strpos is not used in this file.
> ```

Thanks for approving the workflow. Changes made as requested.

**Review by snapshotpl — APPROVED** [review]

**Comment by Ocramius** [comment]
Thanks again! :ship:

**Comment by boesing** [comment]
I already see this conflicting with #98 :-( 
I've removed this as well.

**Comment by Ocramius** [comment]
@boesing happens, heh :-\

**Pull request merged**
