### PR TITLE
Skip `class_alias()` declarations when interfaces were already declared, allowing for usage with preloading

### LINKED ISSUE #128: Cannot declare interface Interop\Container\Exception\NotFoundException, because the name is already in use
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 3.11
| PHP-FPM with opcache.preload enabled | 8.1.4
| Symfony  (with Runtime) | 5.4.7

#### Summary
After upgrading to version 3.11 Im getting all these E_WARNING messages in my logs and monitoring tools.  Im using Symfony 5.4 and FPM with opcache.preload enabled. When I disable preload the warning goes away. 

```
E_WARNING: Cannot declare interface Interop\Container\Containerinterface, because the name is already in use
in class_alias called at /app/vendor/laminas/laminas-servicemanager/src/autoload.php (13)
in require called at /app/vendor/composer/autoload_real.php (55)
in composerRequire6635dcbc130fab9e00890c611d69ace8 called at /app/vendor/composer/autoload_real.php (38)
in ComposerAutoloaderInit6635dcbc130fab9e00890c611d69ace8::getLoader called at /app/vendor/autoload.php (12)
in require_once called at /app/vendor/autoload_runtime.php (5)
in require_once called at /app/public/index.php (9)
```
And also for line 14/15 I get the warning about ContainerException/NotFoundException.

By upgrading to version 3.11 the Interop package got removed. I have no other references to Interop in my generated preload files or any other place. I think its related to opcache.preload, but im not sure.

In a previous version of the src/autoload.php file, there was an `class_exists` check before the alias:
https://github.com/laminas/laminas-servicemanager/commit/0732d65c14962d4aa25c78788cae5bb0a4ac537f#diff-984b8e3111197dd008894b4b1575ffcbda5c801cb8857434cc2898b5dca67873R13

But when I use that version, the warning is still present. 

Downgrading to 3.10.* resolves the issue.

### PR DESCRIPTION
**Pull request by LucasHantz**
Signed-off-by: Lucas Hantz <lucas.hantz@gmail.com>

Fixes #128 
Closes #143

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
@LucasHantz please check inline CI reported errors (you can run `vendor/bin/phpcbf` on that file, if that makes it simpler.

@boesing what's your opinion on this? Should we check if something was autoloaded? This will fix preloading, but it could indeed backfire if somebody else declared those interfaces, and they aren't what we expect (full crash, in that case).

**Comment by LucasHantz** [comment]
Updated with the proper code style

**Comment by boesing** [comment]
@Ocramius TBH: if somebody already used `class_alias` for whatever reason, that might not be our problem.

We either have those users who complain about doing `class_alias` here without a condition or the users who complain about having crashes in their application because whatever other library had used `class_alias` to link to non-PSR interfaces (which might be a super edge-case hopefully).

So lets take that pill and see how that works 🤷🏼‍♂️

**Review by boesing — APPROVED** [review]

**Comment by Ocramius** [comment]
Decided to treat this as feature/compatibility with preloading, hence moving this to `3.13.0` :+1: 

Thanks @LucasHantz

**Pull request merged**
