### PR TITLE
psr/container:^1.0 || ^2.0

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by fezfez** [comment]
@Ocramius it's working but it's a BC i suppose because `Laminas\ServiceManager\ServiceManager` is not marked final ? :/

**Comment by froschdesign** [comment]
@fezfez 
Please check #147

**Comment by fezfez** [comment]
ah, i miss that :facepalm: , maybe it's time to open 4.x ?

**Comment by Ocramius** [comment]
Yep, I think so too.

**Pull request closed without merging**
