### PR TITLE
[Php 7.4] Apply php 7.4 typed property on private property only

### PR DESCRIPTION
**Pull request by samsonasik**
Apply php 7.4 typed property on private property only

### CODE REVIEW

**Comment by Ocramius** [comment]
LGTM, but also here, need to rebase out the "bump changelog" bit :D

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Wait, wtf? What happened to CI runs? O_O

**Comment by samsonasik** [comment]
I don't know, probaly need close - re-open ?

**Comment by samsonasik** [comment]
now running 🎉

**Comment by Ocramius** [comment]
🤷 that did trigger it, thanks!

**Comment by Ocramius** [comment]
@samsonasik opinions on making a new release, vs waiting for new changes?

**Comment by samsonasik** [comment]
new release is fine for me

**Comment by Ocramius** [comment]
New release it is then :) 

Better shipping and observing regressions, than waiting for new stuff to come in half a year 👍

**Comment by desaiuttam** [comment]
Hello @samsonasik @Ocramius 

Typed Property Creates issue still with library and PHP 7.4.23

we are getting the error as below:
main.CRITICAL: ParseError: syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in /home/production/vendor/laminas/laminas-servicemanager/src/ServiceManager.php:115

Updated commit code as:
    /** @var ContainerInterface */
OLD -    private $container;
NEW-    private **?ContainerInterface $container;**
/** Error in New Line **/

    public function __construct(?ContainerInterface $container = null)
    {

Let us know how can we fixed this issue with PHP 7.4.23
Env: Magento 2.4.3 Platform
PHP 7.4.23
Library: laminas/laminas-servicemanager


Thank you,
Uttam

**Comment by samsonasik** [comment]
@desaiuttam it seems you're using multiple php version between cli and web (possibly web version using php 7.3 or vise versa) see https://3v4l.org/9AW1N

**Pull request merged**
